### ISSUE TITLE
[Incident] Cannot access self hosed bitwarden instance because of self-signed certificate

### ISSUE THREAD

**Issue by richardbellat** [maxlaverse/terraform-provider-bitwarden#100]
Hi there,
we have a self hosted on prem bitwarden installation. Access is limited to internal users so we use a self signed certificate from our internal CA.

Access to bitwarden with Bitwarden CLI is running fine. We had to set NODE_EXTRA_CA_CERTS to our CA Certificate correctly. 

Using the Terraform plugin isnt working, I am getting the following error:

Error: 'exit status 1' while running 'login --apikey': , request to https://internal.server.com/identity/connect/token failed, reason: self-signed certificate in certificate chain

   with provider["registry.terraform.io/maxlaverse/bitwarden"],
   on main.tf line 18, in provider "bitwarden":
   18: provider "bitwarden" {

Is there a way to trust our internal CA?

 

**Configuration:**
```
terraform {
required_providers {
  bitwarden = {
    source  = "maxlaverse/bitwarden"
    version = ">= 0.6.3"
    }
  }
}
provider "bitwarden" {
  server="https://internal.server.com"
  email="xxxxx"
  master_password = "yyyyy"
  client_id = "zzzzzz"
  client_secret = "ssssss"
}

```

**Comment by maxlaverse** [comment]
Released in [0.7.0](https://github.com/maxlaverse/terraform-provider-bitwarden/releases/tag/v0.7.0) @richardbellat . Can you try it out ?
