### ISSUE TITLE
Expired GPG key for provider breaks usage with Terraform 1.6.0+

### ISSUE THREAD

**Issue by pa-jberanek** [maxlaverse/terraform-provider-bitwarden#106]
### Terraform Version
1.6.0+

### Affected Resource(s)
All provider usage.

### Terraform Configuration Files
n/a

### Debug Output
```
$ ~/terraform init

Initializing the backend...

Initializing provider plugins...
- Finding maxlaverse/bitwarden versions matching ">= 0.1.1"...
- Installing maxlaverse/bitwarden v0.7.0...
╷
│ Error: Failed to install provider
│
│ Error while installing maxlaverse/bitwarden v0.7.0: error checking signature: openpgp: key expired
╵
```

### Expected Behavior
Provider should be usable.

### Actual Behavior
Provider is not usable.

### Steps to Reproduce
Use Terraform 1.6.0+ and try to use the Bitwarden provider.

### Important Factoids
```
pub   rsa2048 2017-09-04 [SC] [expired: 2023-09-07]
      77728AF1DA38AD17B660D09EECDE241E60988D8C
uid                      Maxime Lagresle <maxime@lagresle.fr>
uid                      Max Laverse <max@laverse.net>
uid                      Maxime Lagresle <maxime.lagresle@xing.com>
uid                      Maxime Lagresle <maxime.lagresle@new-work.se>
uid                      Maxime Lagresle <maxime@angel.co>
sub   rsa2048 2017-09-04 [E] [expired: 2023-09-07]
sub   rsa3072 2020-12-02 [S] [expired: 2022-12-02]
sub   rsa3072 2020-12-02 [A] [expired: 2023-09-07]
sub   rsa3072 2021-07-13 [S] [expired: 2023-07-13]
sub   rsa3072 2022-01-16 [S] [expired: 2023-09-07]
```

**Comment by maxlaverse** [comment]
Sorry for the inconvenience @pa-jberanek. I released [version 0.7.1 ](https://github.com/maxlaverse/terraform-provider-bitwarden/releases/tag/v0.7.1)with my renewed GPG key.

**Comment by maxlaverse** [comment]
The missing part is that I can't update my GPG key on Hashicorp's Terraform Registry. I wrote to their support, ut I never got an answer when I tried to reach out to them in the past. In the meantime, it seems they're rolling back this _expiry validation_ when installing the providers: https://github.com/hashicorp/terraform/commit/0d4a29f7f3968d3d7d9199f9c5bd10759acb934b

This should remove the error you're seing.

**Comment by larivierec** [comment]
just tested this with 1.6.1, fixes the issue. 👍

**Comment by maxlaverse** [comment]
Ah perfect, thanks for the feedback @larivierec.
I'll close the issue, giving more time to Hashicorp support to eventually answer. If they don't and bring back GPG expiry validation, I assume the only option will be to signed the release with a completely new key

**Comment by maxlaverse** [comment]
Hashicorp replied saying they have no plan to bring back GPG expiry validation after a provider is published. We should be good!
