### ISSUE TITLE
[FEATURE] Bitwarden Secret Manager

### ISSUE THREAD

**Issue by joryirving** [maxlaverse/terraform-provider-bitwarden#137]
Any plans to support Bitwarden Secrets Manager? They have a CLI available.
<https://bitwarden.com/help/secrets-manager-cli/>

I'd also love to hit the API directly, rather than having to ensure the CLI tool is installed.

**Comment by firatkucuk** [comment]
I come to enter this feature request. Yes, that would be really good.

**Comment by maxlaverse** [comment]
Hi! I've implemented experimental support for using the provider without requiring the Bitwarden CLI to be installed. it's not yet the Bitwarden Secrets Manager, but it would partially answer your feature request I assume. If you have the opportunity, please give it a try! I appreciate any feedback.

**Comment by maxlaverse** [comment]
Thanks for the quick feedback @joryirving !
I just released a patch version for the issue you faced. Unfortunately, the error occurs because something went wrong with the authentication. I'd love to understand why: the response of the server should appear in the standard outputs.

**Comment by maxlaverse** [comment]
I can reproduce actually, at least I get a `No device information provided` error. Will look into it!

**Comment by joryirving** [comment]
Perfect, that's the same error I'm seeing on 0.9.1.

```
│ Error: error login with api key: bad response status code for 'https://vault.bitwarden.com/identity/connect/token': 400!=200, body:{"error":"invalid_grant","ErrorModel":{"Message":"No device information provided.","Object":"error"}}
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on providers.tf line 1, in provider "bitwarden":
│    1: provider "bitwarden" {
│ 
```

**Comment by joryirving** [comment]
It appears to work for me! I look forward to potential integration with the secret manager as well.

**Comment by maxlaverse** [comment]
Hi @joryirving 
I just released [v0.10.0](https://github.com/maxlaverse/terraform-provider-bitwarden/releases/tag/v0.10.0) with experimental support for Bitwarden Secrets. There is still work to do to increase test coverage, but the base is here with machine account authentication and management of the secret resource.

Since covering the entire API of the Bitwarden Secrets Manager could represent quite some work, I'd propose to create new issues for more specific feature requests. ACLs aren't supported at this point for example, but it might no be needed right away if people use the provider to _read_ secrets rather than _create_ them.

If you have the opportunity, please give it a try! I appreciate any feedback.

**Comment by larivierec** [comment]
FYI, i'm not sure this is testable but I did convert my login item from password manager to a secrets manager with this 

```
│ Error: error creating secret: error doing request to 'https://vault.bitwarden.com/api/organizations/<REDACTED>/secrets': POST https://vault.bitwarden.com/api/organizations/<REDACTED>/secrets giving up after 5 attempt(s)
│
│   with bitwarden_secret.this["wireguard_public"],
│   on main.tf line 14, in resource "bitwarden_secret" "this":
│   14: resource "bitwarden_secret" "this" {
│
```

as i'm trying to move towards secrets manager and I think I received a 429 error but masked.
tried to create roughly 57 secrets.

i had to do TF Apply twice for it to work properly.
just a small headsup to those who are creating a lot of secrets.

**Comment by joryirving** [comment]
Thanks I will try it out! I already have a feature request in mind that I hope to open shortly.

**Comment by maxlaverse** [comment]
@larivierec I can reproduce, and it requires changing the underlying http client to be smarter about 429s. I'll create an issue for it
