### ISSUE TITLE
[provider auth] Use client id and secret without master_password

### ISSUE THREAD

**Issue by Aletor93** [maxlaverse/terraform-provider-bitwarden#156]
### Terraform Version
```
Terraform v1.9.5
on linux_amd64
+ provider registry.terraform.io/maxlaverse/bitwarden v0.8.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- provider authentication using client_id and client_secret

### Terraform Configuration Files
```hcl
terraform {
  ...
  required_providers {
    bitwarden = {
      source = "maxlaverse/bitwarden"
      version = "0.8.1"
    }
  }
}

provider "bitwarden" {
  # Relies on environment variables
  # - BW_CLIENTID
  # - BW_CLIENTSECRET
}
```

### Debug Output
https://gist.github.com/Aletor93/53752ef7e2f147f1b597274a2c12a66a

### Panic Output
n/a

### Expected Behavior

Following this: https://registry.terraform.io/providers/maxlaverse/bitwarden/latest/docs#generating-a-client-id-and-secret

Authentication using client ID and secret only should work, like here: https://bitwarden.com/help/api/

### Actual Behavior

When using auth based on client ID and secret, both email and master_password are also required.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Define an empty `bitwarden` provider
2. Define both environment variables `BW_CLIENTID` and `BW_CLIENTSECRET` 
3. Run `terraform apply`

### Important Factoids
n/a

### References
n/a

**Comment by maxlaverse** [comment]
Hi @Aletor93! I'll have a look later and relax the constraint if it's not necessary.

**Comment by Aletor93** [comment]
Hi,

I didn't want to bother you with this issue, as the documentation is clear and the error message too: email, password, client_id and client_secret are required. 

However, I think it might be more secure to just rely on using client_id and client_secret. 

I looked briefly at the provider code in Go (I'm not a dev), I thought maybe I could contribute. But thinking about it, I tell myself that it might be even better to go through the API rather than relying on the client installed on the host. 

It is for these reasons that I closed the issue and headed towards hashicorp vault for the moment. However, I am interested in your project.

Regards,

**Comment by maxlaverse** [comment]
I realize only today that I hadn't properly answered that issue. Two additional notes:
1. The _email_ isn't required when using API keys anymore when using the embedded client, and I'm updating the CLI integration + documentation to have this consistent.
2. The documentation Aletor93 had pointed at (https://bitwarden.com/help/api/) is for the public API of Bitwarden, which is different that managing a Vault. Yes, you don't need a master password when talking to the public API with API keys, but you still need it if you want to do any decrypting/encrypting operation (as far as I know)
