### ISSUE TITLE
[BUG] Provider throws error when configured for secret manager.

### ISSUE THREAD

**Issue by joryirving** [maxlaverse/terraform-provider-bitwarden#173]
### Terraform Version
1.9.7

### Affected Resource(s)
N/A

### Terraform Configuration Files
https://github.com/joryirving/home-ops/blob/336d9de1ce69aaa52a21a5a2035f68a0021628e1/terraform/minio/providers.tf

### Debug Output
```
│ Error: provider was not configured with Password Manager credentials
│ 
│ 
╵
╷
│ Error: provider was not configured with Password Manager credentials
│ 
│ 
```

### Expected Behavior
Terraform is able to apply

### Actual Behavior
Terraform plans with the error, and the apply gets almost done, but exits before confirming due to the error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Configure provider for Bitwarden Secret manager (access token), but not password login
2. `Terraform plan`

**Comment by maxlaverse** [comment]
Could it be that you still have Password Manager-based resources in your state (e.g login, secure note, folders) but removed their declaration ? The provider wouldn't know how to delete them, which could lead to such an error

**Comment by joryirving** [comment]
Bad state was the answer, thanks!
