### ISSUE TITLE
`concurrent map writes` when using the experimental embedded client

### ISSUE THREAD

**Issue by aeber** [maxlaverse/terraform-provider-bitwarden#182]
### Terraform Version
```
OpenTofu v1.8.4
```

### Affected Resource(s)

This might affect all resources with the embedded client. I observed errors with the following resources:
- bitwarden_item_login
- bitwarden_item_secure_note

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    bitwarden = {
      source  = "maxlaverse/bitwarden"
      version = ">= 0.11.0"
    }
  }
}

provider "bitwarden" {
  email    = "test@example.com"
  master_password = "test1234"

  server = "http://localhost:8080"

  experimental {
    embedded_client = true
  }
}

resource "bitwarden_item_login" "many" {
  count    = 200
  name     = "Login Item ${count.index + 1}"
  username = "admin"
  password = "password"
}
```

### Debug Output

https://gist.github.com/aeber/5f17496bec4612976c2339b3d9a2da05

### Expected Behavior

The provider should have created all elements without error.

### Actual Behavior

The provider crashed with:
```
fatal error: concurrent map writes
```

### Steps to Reproduce
1. `terraform apply` with a high enough `count` on the `bitwarden_item_login` resource.

### Possible solutions

In my tests this error could be resolved by wrapping every access to `objectStore` in `internal/bitwarden/embedded/password_manager_base.go` with a mutex.

**Comment by maxlaverse** [comment]
Thanks a lot for the report and reproduction case @aeber. I'll fix this soon and try to case other similar concurrency issues in the code base.

**Comment by maxlaverse** [comment]
Released in https://github.com/maxlaverse/terraform-provider-bitwarden/releases/tag/v0.11.1
