### ISSUE TITLE
Support Folder creation

### ISSUE THREAD

**Issue by Nepo26** [maxlaverse/terraform-provider-bitwarden#191]
Hi there, I think the support for the creation of folders as opposite to setting it read only will 
be a great addition, as it makes it easier to manage our defined folders and general definitions. 

It seems to be feasible as the _bitwarden cli_ [allows for a folder creation as well](https://bitwarden.com/help/cli/#create).

Do you need any help with anything?

**Comment by maxlaverse** [comment]
Hi @Nepo26 ,
I'm sorry, I didn't fully understand. There is already a [folder resource](https://registry.terraform.io/providers/maxlaverse/bitwarden/latest/docs/resources/folder) allowing the creation a folders right ? They can be modified as well. What did you mean with _setting it read-only_ ?

**Comment by maxlaverse** [comment]
I'm going to close the issue, but please re-open it if this is confirmed to be a problem
