### ISSUE TITLE
[Feature request] Ability to support URI on item login resource

### ISSUE THREAD

**Issue by dannykitchen** [maxlaverse/terraform-provider-bitwarden#51]
### Terraform Version
Latest

### Affected Resource(s)
bitwarden_item_login

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
NA

### Debug Output
NA

### Panic Output
NA

### Expected Behavior

Allow the ability to populate the URI on item login resource on bitwarden vault

### Actual Behavior
Does not support this ? 

### Steps to Reproduce
NA

### Important Factoids
NA

### References
NA

**Comment by maxlaverse** [comment]
Hi @dannykitchen 
You're looking for the ability to configure URIs that are used to match a set credentials with a specific website is that correct ?

**Comment by dannykitchen** [comment]
hi @maxlaverse - requirement to populate the website URL field on creation of a credential
