### ISSUE TITLE
Receiving 'Rate limit exceeded' error on high number of api calls

### ISSUE THREAD

**Issue by leynebe** [maxlaverse/terraform-provider-bitwarden#61]
### Terraform Version
```
$ terraform -v
Terraform v1.3.7
on linux_amd64
```

### Affected Resource(s)
- `bitwarden_item_login`

### Terraform Configuration Files
```hcl
resource "bitwarden_item_login" "app" {
  name            = "${local.bw_item_prefix}-app"
  username        = local.APP_USER
  password        = local.APP_PASSWORD
  organization_id = local.bw_organization_id
  notes           = local.bw_notes
  favorite        = false
  collection_ids  = [local.bw_collection_app]

  uri {
    value = local.domain
  }

  dynamic "field" {
    for_each = local.bw_fields
    content {
      name = field.key
      text = field.value
    }
  }

  field {
    name = "service"
    text = "app"
  }
}
```

### Debug Output
Unfortunately I cannot provide this due to the sensitive nature of the project.

### Panic Output
Unfortunately I cannot provide this due to the sensitive nature of the project.

### Expected Behavior
* Successful creation of many Bitwarden login items.

### Actual Behavior
* Many of these errors:
    ![image](https://user-images.githubusercontent.com/34703148/216276111-7e33be8f-cb89-4e63-9f94-50d3ca3de96c.png)
* Applying a second time creates the remaining items.

### Steps to Reproduce
1. `terraform apply`
2. `yes`
3.  Many item creation failures with 'Rate limit exceeded. Try again later.' error.` (I tried finding this error in the source code of Bitwarden repos and this provider repo but it shows up nowhere.)

### Important Factoids
This is probably not an issue with this provider, but I'm creating this anyway because I cannot find any information anywhere if a rate limit is implemented (on this provider, bitwarden cli or bitwarden api). Bitwarden may not understand why lots of API calls are happening, unfortunately this is pretty much how Terraform works. So I'm hoping to gather more information through this ticket so I can create a more full ticket on the bitwarden community forum, and so I can reference this ticket. (EDIT: I created a ticket there too: https://community.bitwarden.com/t/rate-limit-exceeded-error-on-high-number-of-bitwarden-cli-calls/50203)

### References
I found some community posts which seem related:
* https://community.bitwarden.com/t/rate-limiting-on-the-api/47995/2
* https://community.bitwarden.com/t/is-there-a-rate-limit-in-server-cli-or-is-it-just-buggy/33313

**Comment by maxlaverse** [comment]
Hi @leynebe ! Thanks for reporting this issue. It's not a nice user experience and I actually encountered a similar issue myself, last week, with another provider.

As you suggested, the error doesn't come from the provider but is thrown by the Bitwarden CLI. Out of curiosity, how many resources are we talking about when this issue happened, existing and created ? I'd like to get a feeling of where the limit is.

One thing we could do is to try to detect this kind of error when a Bitwarden CLI command is unsuccessful, and retry a couple of times, with an exponential back off. After all, it can very likely only be faster to wait a bit and retry a few commands, than having the whole _apply_ fail and needing to rerun everything.

I removed one superfluous 'sync' call in the latest release. We're you using this version ?

**Comment by leynebe** [comment]
Hey @maxlaverse, thanks for the quick response!

> As you suggested, the error doesn't come from the provider but is thrown by the Bitwarden CLI. Out of curiosity, how many resources are we talking about when this issue happened, existing and created ? I'd like to get a feeling of where the limit is.

I only have 13 `bitwarden_item_login` resources, so it's not even that many to be honest. In our case I wouldn't be surprised if this went to 20 soon.

> I removed one superfluous 'sync' call in the latest release. Were you using this version ?

We were still using `0.4.0`. You're talking about `0.5.0` I'm assuming? I'll try it out and let you know.

**Comment by leynebe** [comment]
Just because I was curious I tried creating the 13 resources from scratch a couple of times and it looks like it stops working right around 10-11 items.
* First run: `10/13` created
* Second run: `11/13` created
* Third run: `10/13` created

**Comment by leynebe** [comment]
For `0.5.0` the results improved but barely:
![image](https://user-images.githubusercontent.com/34703148/216552860-70587a72-53a6-4001-ba37-e0b808960603.png)
* First run: `11/13` created
* Second run: `12/13` created
* Third run: `11/13` created

**Comment by leynebe** [comment]
This might warrant its own ticket but I'm also occasionally encountering a failure in tf refresh of login items when applying (after a failed apply):
![image](https://user-images.githubusercontent.com/34703148/216559774-aef38898-bed5-411a-919b-aab3762f8d17.png)
This error happens until I do a `bw sync` locally, which is weird because we pass static credentials to the provider:
![image](https://user-images.githubusercontent.com/34703148/216559898-6af8151a-e178-4afb-aad5-3dd07d022926.png)
so is it possible that my `bw login` user is interfering with the user defined in the provider when doing a tf apply?
It might also have to do with the fact that my apply is erroring out due to the issues above and a proper `bw sync` never happens from the provider's perspective.

**Comment by leynebe** [comment]
We implemented a temporary fix by chaining resources with `depends_on` so Terraform waits for the creation of one secret before continuing with the next.

**Comment by maxlaverse** [comment]
I didn't manage to come back to my PR for the past weeks, but I haven't forgotten about the issue and have a PR that was almost finished iirc. Glad to hear you have a temporary fix @leynebe

**Comment by maxlaverse** [comment]
I refactored the command execution a bit and added retries with back-off on rate limiting errors @leynebe !. If you have the opportunity to try the latest version out in the next week and give some feedback, that'd would great.

**Comment by leynebe** [comment]
@maxlaverse Thank you for the effort. I unfortunately no longer work for the company whose codebase prompted me to create this issue, but I have forwarded this issue to the people responsible for the codebase.

**Comment by maxlaverse** [comment]
Oh alright. Thanks and all the best with what's next
