### ISSUE TITLE
[bug] Possible bug when using apikey login

### ISSUE THREAD

**Issue by Magister-Machinis** [maxlaverse/terraform-provider-bitwarden#93]
Hello,
I'm not sure if this is a true bug or if I've misconfigured something. When attempting to run a plan action in terraform 1.5.2 with the 0.6.1 bitwarden  provider I get an error stating the below. However I am not using organization keys and if I run bw.exe --apikey separately the login attempt is successful. I'm running this on windows 11 .  As for reproducing it, the startupcommands is the cmd script I'm using to run this. Any insights on what I may have missed would be appreciated, happy to provide any other info that may be useful.

│ Error: 'exit status 1' while running 'login --apikey': , Invalid API Key; Organization API Key currently not supported
│
│   with module.Docker.provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on Docker_Clusters\Providers.tf line 10, in provider "bitwarden":
│   10: provider "bitwarden" {

Gist with relevant files: https://gist.github.com/43a01d61b1f7a1b3262edbc8bf291952.git

**Comment by Magister-Machinis** [comment]
Quick update, tried this with the v2023.1.0 cli to be certain of compatibility and get the same error.

**Comment by maxlaverse** [comment]
Hi @Magister-Machinis! Sorry for the last reply. Could you run the terraform command with additions logs, e.g. by running export TF_LOGS=debug beforehand ?

You should be able to confirm the command that is sent to the Bitwarden CLI, especially the parameters. Any chance Terraform uses a different executable than when you try out things manually ?

**Comment by Magister-Machinis** [comment]
No worries! I added another log to the gist and made sure it had debug info if that is helpful. Let me know if any other info could be useful.

**Comment by maxlaverse** [comment]
Thanks again for the gist.

I was trying to play around the _login_ command with my local Bitwarden client which is actually 2023.5.0. Interestingly, by entering non-sense as `client_id` and `client_secret`, I got the same result as you:
```
bw login --apikey
? client_id: bla
? client_secret: bla
Invalid API Key; Organization API Key currently not supported
```

More specifically, I got this error when using a `client_id` value that wouldn't start with `user.*`. Messing up with the end of those two fields would end up with the error `Invalid client_id` or `Incorrect client_secret` but nothing about Organization  API Keys.

Now I'm curious: if there is a dot in your `client_id`, what's in front of it ?
It seems the error message you're seeing comes from a server-side validation, so I would think something is wrong with the `client_id` being used:
* typo in the value
* not set properly by the provider
* not read properly by the cli

> if I run bw.exe --apikey separately the login attempt is successful. 

Could you try setting the `BW_CLIENTID` and `BW_CLIENTSECRET` environment variable, and then run `bw.exe login --api-key`, like the provider does ? From a different angle, could you try hard-coding the values in the `provider "bitwarden" {}` declaration, just in case ?

Thanks!

**Comment by Magister-Machinis** [comment]
So running bw.exe login --apikey with the secret and id as environment variables works. Interestingly hard coding the id, secret, and pw also works in tf plan. Passing them as variables seems to be the issue. did some poking and found that removing quotes from variables being passed in seems to fix this! Thank you for help with troubleshooting, would a bit of input sanitization to remove leading/trailing quotes be possible?

**Comment by maxlaverse** [comment]
Glad you sorted it out!
Sanitization definitely makes sense, and maybe those field have a format we could add to the provider's schema for validation.

**Comment by Magister-Machinis** [comment]
Great, thanks again for the assistance.
