### ISSUE TITLE
Using session key when applying from plan produces unauthenticated error

### ISSUE THREAD

**Issue by Poulpatine** [maxlaverse/terraform-provider-bitwarden#95]
Hi,

first of all thanks for this very useful provider ! :)

### Terraform Version
Terraform v1.1.7 / v1.5.3

### Affected Resource(s)
Please list the resources as a list, for example:
- bitwarden_item_login

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "elasticstack" {
  elasticsearch {}
}

provider "bitwarden" {
  session_key = var.bw_session
  vault_path  = var.bw_vault
  email       = "xxx-xxx@yyy.zzzx"
  server      = "https://vault.xxx.yyy.zzz"
}

terraform {
  required_version = ">= 1.1.2"
  required_providers {
    bitwarden = {
      source  = "maxlaverse/bitwarden"
      version = ">=0.6.1"
    }
    elasticstack = {
      version = ">=0.6.2"
      source  = "elastic/elasticstack"
    }
  }
}
```

### Expected Behavior
Apply should work directly.

### Actual Behavior
```
Terraform has been successfully initialized!
╷
│ Error: unable to unlock Vault with provided session key (status: unauthenticated)
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on provider.tf line 5, in provider "bitwarden":
│    5: provider "bitwarden" {
│ 
╵
```

### Steps to Reproduce
First of all, I'm using a private vaultwarden instance instead of official bitwarden.

vault_path content has been manually copied from a login with bw cli.
session_key has been manually copied from a login with bw cli.

Both values are passed from the CI configuration.

First job:
`terraform plan -intput=false -out="plan.cache`
plan.cache file is passed as an artifact from first job to second one.

Second job;
`terraform apply -intput=false "plan.cache"`

If a new terraform plan is launched, then the apply is ok.

Does vault local content and terraform plan could be linked in any way ?

**Comment by maxlaverse** [comment]
Hi @Poulpatine !
Thanks for gathering this information.

> vault_path content has been manually copied from a login with bw cli.

Could you elaborate on this ? Do you mean you copied the local Vault from the default path to another location, and you specified this other location as `vault_path` in the provider's configuration ?

I understand than you generate a plan as a first step, and then execute the plan as a second step, is that correct ?

> If a new terraform plan is launched, then the apply is ok.

What do you mean by that ?

In general, I'm very interested in your your case here. Why did you decide to provide a session key instead of giving the provider credentials, so you don't have to login manually: trust ?

> If a new terraform plan is launched, then the apply is ok.

If you provide a session key, I think you need to either:
1. change the `vault_path` to the actual path of your local Vault (depends on the OS)
2. or run
  a.`export BITWARDENCLI_APPDATA_DIR=./.bitwarden/`
  b. `cd <your-terraform-workspace>/`
  c.`bw config server <your-server-url>`
  d.`bw login`

**Comment by Poulpatine** [comment]
vault_path content has been manually copied from a login with bw cli.

I mean that the data.json content has been copied a single time manually from $BITWARDENCLI_APPDATA_DIR/data.json in a variable. And the content of this variable is used at each Terraform run with :

```yaml
# BW_VAULT is the content of data.json located in 
# TF_VAR_bw_vault is used as vault_path
   - export TF_VAR_bw_vault=$(mktemp -d)
   - cat "${BW_VAULT}" > ${TF_VAR_bw_vault}/data.json
```


    If a new terraform plan is launched, then the apply is ok.

When I use the plan.cache generated from the first job. my terraform apply fails. But if I generate a new one with `terraform plan -intput=false -out="plan.cache"` it goes well.


The reason I use a session key is that I just want to avoid to receive a "new device" email at each CI run.

**Comment by maxlaverse** [comment]
Thanks! It's a bit more clear.
You mean that the apply doesn't work if you run _apply_ in a separate job, but if you run _plan_ and _apply_ in a row you don't face the error is that right ?

I'm surprised you get a notification every time the provider runs. I also have a Vaultwarden Vault for one of my projects, and I don't get notifications that often. Have you tried using a Client ID and Client Secret ?

**Comment by Poulpatine** [comment]
> You mean that the apply doesn't work if you run apply in a separate job, but if you run plan and apply in a row you don't face the error is that right ?

Yes, exactly.

> I'm surprised you get a notification every time the provider runs. I also have a Vaultwarden Vault for one of my projects, and I don't get notifications that often. Have you tried using a Client ID and Client Secret ?

You mean, by only passing Client ID and Client Secret to the provider ?

If that's it, I've just made a test and I face the following error:
```
Terraform has been successfully initialized!
Initializing provider plugins...
- Reusing previous version of elastic/elasticstack from the dependency lock file
- Reusing previous version of maxlaverse/bitwarden from the dependency lock file
- Using previously-installed maxlaverse/bitwarden v0.6.1
- Using previously-installed elastic/elasticstack v0.6.2
Terraform has been successfully initialized!
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on provider.tf line 5, in provider "bitwarden":
│    5: provider "bitwarden" {
│ 
│ "master_password": one of `master_password,session_key` must be specified
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on provider.tf line 5, in provider "bitwarden":
│    5: provider "bitwarden" {
│ 
│ "session_key": one of `master_password,session_key` must be specified
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on provider.tf line 6, in provider "bitwarden":
│    6:   client_id     = var.bw_client_id
│ 
│ "client_id": all of `client_id,client_secret,master_password` must be
│ specified
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on provider.tf line 7, in provider "bitwarden":
│    7:   client_secret = var.bw_client_secret
│ 
│ "client_secret": all of `client_id,client_secret,master_password` must be
│ specified
╵
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by maxlaverse** [comment]
> Yes, I'm providing client ID / Secret in addition to Master password but I get an email every time.

Which version of Vault Warden do you have ? I'm still running on 2022.12.0. I just checked: login in from the UI results in an email, but not using Terraform. I do have MFA enabled with the account (if it makes any difference).

> Yes, exactly.

Have you tried comparing the content of both plans, to find out if there are any obvious difference @Poulpatine ? I must admit I don't know how those session keys are generated. I have to read about that. 

Could you eventually try plan+apply, but with a session key from the Vault the Terraform Provider is using ?

**Comment by Poulpatine** [comment]
I'm using Vaultwarden ` Version 2023.5.0 `.
I've made a test this morning with MFA but I've also received a mail.

On your suggestion I've compared both plans and the only different thing was the TF_VAR_bw_vault.
Hence, I've modified my CI to use a fixed location for the vault_path and now the problem is fixed.

Sorry for the noise and many thanks for your help. 
We can close the issue.

**Comment by maxlaverse** [comment]
Alright, good to know!
