### ISSUE TITLE
Text fields created by provider are not visible by GUI clients

### ISSUE THREAD

**Issue by jollyroger** [maxlaverse/terraform-provider-bitwarden#96]
### Terraform Version
1.5.4

### Affected Resource(s)
Please list the resources as a list, for example:
- bitwarden_item_login

### Terraform Configuration Files
```hcl
resource "bitwarden_item_login" "this" {
  name        = "server"
  username = var.ssh_user
  password = var.ssh_pass

  field {
    name    = "test"
    text    = "passed"
  }
}
```

### Expected Behavior
A "login" item is created in Bitwarden with an additional "test" text field visible in Bitwarden HTTP or GUI client. 

### Actual Behavior
A text field is visible using `bw` CLI tool only. The queried parameter looks like this(some attributes ommitted for brevity):

```json
{
  "object": "item",
  "id": "80098baa-0966-4758-89af-0831ae33c58c",
  "organizationId": null,
  "folderId": null,
  "type": 1,
  "reprompt": 0,
  "name": "server",
  "notes": null,
  "favorite": false,
  "fields": [
    {
      "name": "test",
      "value": "passed"
    }
  ],
  "login": {
    "username": "root",
    "password": "secret",
    "totp": null,
    "passwordRevisionDate": null
  },
  "collectionIds": [
  ],
  "revisionDate": "2023-08-01T22:59:05.915Z",
  "creationDate": "2023-08-01T22:41:35.031Z",
  "deletedDate": null
}
```

here we can see an expected attribute is defined as:
```json
    {                             
      "name": "test",
      "value": "passed"
    } 
```

however, when the same parameter is created manually it looks like this:
```json
    {                             
      "name": "test",                                               
      "value": "passed",                                            
      "type": 0,                  
      "linkedId": null            
    } 
```
we can see currently there are "type" and "linkedId" attributes missing. The "type" attribute is the most important here, without it the value is not visible in the Bitwarden GUI or web GUI.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Reproduced on a self-hosted Vaultwarden server

**Comment by maxlaverse** [comment]
Thanks for all the details @jollyroger ! I'll try to fix this as soon as I can

**Comment by maxlaverse** [comment]
@jollyroger The fix is on master. I'll see if I can ship other small changes a the next days and release a new version

**Comment by maxlaverse** [comment]
Released @jollyroger

**Comment by jollyroger** [comment]
Thanks a lot! I've tested and it works as expected!
